<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f5f7fb"><title>Collaboration  |  DataHive</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/app.css?v=20261010-polish2"></head>
<body class="app-page"><div class="app-shell"><%@ include file="fragments/sidebar.jspf" %>
<main class="main-content"><header class="topbar"><button class="mobile-menu" type="button" data-menu-toggle aria-label="Toggle navigation"><span class="menu-glyph" aria-hidden="true"></span></button><div class="breadcrumbs"><span>Workspace</span><span class="crumb-divider">/</span><strong>Collaboration</strong></div><div class="topbar-actions"><span class="environment-pill"><span></span> LOCAL WORKSPACE</span><button class="icon-button notification-trigger" type="button" data-notification-toggle aria-expanded="false" aria-controls="notification-panel" aria-label="Notifications" title="Notifications"><svg viewBox="0 0 20 20" aria-hidden="true" focusable="false"><path d="M15.5 8a5.5 5.5 0 0 0-11 0c0 6-2 6-2 7.5h15C17.5 14 15.5 14 15.5 8ZM8 18h4"/></svg><span class="notification-badge" data-notification-badge hidden></span></button><button type="button" class="top-avatar account-menu-trigger" data-account-menu-toggle aria-expanded="false" aria-controls="account-menu-panel" aria-label="Open account menu" title="Account menu"><span data-profile-initials><c:out value="${initials}"/></span><img class="profile-photo-image" data-profile-photo alt="" hidden></button></div></header>
<div class="page-wrap"><section class="welcome-row"><div><p class="eyebrow">SHARED RESEARCH</p><h1>Collaboration</h1><p class="page-intro">Manage project teams and see who has access to each research workspace.</p></div></section>
    <c:if test="${param.notice eq 'updated'}"><div class="alert alert-success" role="status">Project team updated.</div></c:if>
    <c:if test="${param.error eq 'member'}"><div class="alert alert-error" role="alert">That researcher could not be added or removed. Refresh the team list and try again.</div></c:if>
    <c:choose><c:when test="${empty projects}"><section class="panel project-empty collaboration-empty"><span class="empty-mark">CO</span><h3>No active projects</h3><p>Create or join an active project to manage its research team.</p><a class="button button-primary" href="${pageContext.request.contextPath}/projects">View projects</a></section></c:when><c:otherwise>
        <section class="collaboration-project-bar"><form method="get" action="${pageContext.request.contextPath}/collaboration"><label for="team-project">Active project</label><select id="team-project" name="project" onchange="this.form.submit()"><c:forEach var="project" items="${projects}"><option value="<c:out value='${project.id}'/>" <c:if test="${not empty selectedProject and selectedProject.id eq project.id}">selected</c:if>><c:out value="${project.title}"/>  |  <c:out value="${project.ownerName}"/></option></c:forEach></select><noscript><button class="button button-secondary" type="submit">Open team</button></noscript></form></section>
        <c:if test="${not empty selectedProject}">
            <section class="collaboration-layout">
                <article class="panel team-panel"><div class="panel-heading"><div><p class="eyebrow">PROJECT ROSTER</p><h2><c:out value="${selectedProject.title}"/></h2></div><span class="team-count"><c:out value="${members.size()}"/> members</span></div>
                    <c:if test="${not empty selectedProject.description}"><p class="team-project-description"><c:out value="${selectedProject.description}"/></p></c:if>
                    <div class="team-member-list"><c:forEach var="member" items="${members}"><article class="team-member"><span class="team-avatar"><c:out value="${member.initials}"/></span><span class="team-member-copy"><strong><c:out value="${member.fullName}"/></strong><small><c:out value="${member.email}"/></small></span><span class="member-role-pill role-${member.roleLabel}"><c:out value="${member.roleLabel}"/></span>
                        <c:if test="${canManageMembers and member.memberRole eq 'RESEARCHER'}"><form method="post" action="${pageContext.request.contextPath}/collaboration" data-confirm="Remove this researcher from the project? They will lose access to its datasets and experiments."><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}'/>"/><input type="hidden" name="action" value="remove"/><input type="hidden" name="projectId" value="<c:out value='${selectedProject.id}'/>"/><input type="hidden" name="userId" value="<c:out value='${member.id}'/>"/><button class="text-action text-action-muted" type="submit">Remove</button></form></c:if>
                    </article></c:forEach></div>
                </article>
                <c:if test="${canManageMembers}"><aside class="panel invite-panel"><div class="invite-icon">+</div><p class="eyebrow">TEAM ACCESS</p><h2>Add a researcher</h2><p>Researchers added here can access the project's datasets and experiments.</p><c:choose><c:when test="${empty availableResearchers}"><div class="invite-empty">There are no other active researcher accounts available. An admin can create one in Administration.</div></c:when><c:otherwise><form method="post" action="${pageContext.request.contextPath}/collaboration"><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}'/>"/><input type="hidden" name="action" value="add"/><input type="hidden" name="projectId" value="<c:out value='${selectedProject.id}'/>"/><label for="invite-user">Researcher account</label><select id="invite-user" name="userId" required><option value="">Choose a researcher</option><c:forEach var="researcher" items="${availableResearchers}"><option value="<c:out value='${researcher.id}'/>"><c:out value="${researcher.fullName}"/>  |  <c:out value="${researcher.email}"/></option></c:forEach></select><button class="button button-primary invite-submit" type="submit">Add to project <span>-&gt;</span></button></form></c:otherwise></c:choose></aside></c:if>
            </section>
        </c:if>
    </c:otherwise></c:choose>
    <footer class="page-footer"><span>DataHive Research Platform</span><span>Project membership controls access to research records.</span></footer>
</div></main></div><script src="${pageContext.request.contextPath}/assets/js/app.js?v=20261008-photo-menu4" defer></script></body></html>
